export function generateAnnexPlaceholders(rows, tipoAnexo) {
  return rows.map((row) => ({
    id: crypto.randomUUID(),
    anexo_id: crypto.randomUUID(),
    operacion_id: row.operacion_id,
    factura_id: row.factura_id,
    tipo_anexo: tipoAnexo,
    version_anexo: 'v1',
    estado: 'Preparado',
    link_anexo_word: `pendiente/${row.factura || row.factura_id}-${tipoAnexo.replaceAll(' ', '-')}.docx`,
    link_anexo_pdf: '',
    variables: {
      originador: row.originador,
      cliente: row.cliente,
      ruc_cliente: row.ruc_cliente,
      obligado: row.obligado,
      ruc_obligado: row.ruc_obligado,
      codigo_obligado: row.codigo_obligado,
      factura: row.factura,
      fecha_vencimiento: row.fecha_vencimiento,
      moneda: row.moneda,
      monto_neto_pago: row.monto_neto_pago,
      monto_financiado: row.monto_financiado_saldo_capital,
      tasa: row.tasa,
      margen_cobertura: row.margen_cobertura,
      participante_origen_nombre: row.requiere_datos_participante === 'Si' ? row.participante_origen_nombre : '',
      participante_origen_ruc: row.requiere_datos_participante === 'Si' ? row.participante_origen_ruc : '',
      codigo_valor_cavali: row.codigo_valor_cavali,
    },
  }));
}
